# please run below steps.
# 1. docker-compose up php-dev
# 2. docker-compose exec php-dev bash
# 3. (in docker container) cd /laravel/lib
# 3. (in docker container) php artisan serve --host 0.0.0.0
version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: trade
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - data-volume:/var/lib/mysql

  db-gui:
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    ports:
      - "8001:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

volumes:
  logs:
    driver: local
  data-volume:

